services:
  db:
    image: mysql:8.0
    container_name: mysql-todo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password1.
      MYSQL_DATABASE: todo
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring-network

  app:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - spring-network

volumes:
  db_data:

networks:
  spring-network:
